version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  syntax-check:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Check Python syntax
          command: python -m compileall .

  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Build Application
          command: echo "Building application..."

  test-interface:
    parallelism: 2
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Test Interface
          command: echo "Running interface tests..."

  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying to production..."
      - run:
          name: Notify Deployment Success
          command: 'curl -X POST --data-urlencode "payload={\"text\": \"Deployment successful.\"}" YOUR_WEBHOOK_URL'

workflows:
  version: 2
  build_and_test:
    jobs:
      - syntax-check
      - build:
          requires:
            - syntax-check
      - test-interface:
          requires:
            - build
  deploy_application:
    jobs:
      - deploy:
          requires:
            - test-interface
